// Code generated by entc, DO NOT EDIT.

package code

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the code type in the database.
	Label = "code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldContents holds the string denoting the contents field in the database.
	FieldContents = "contents"
	// Table holds the table name of the code in the database.
	Table = "codes"
)

// Columns holds all SQL columns for code fields.
var Columns = []string{
	FieldID,
	FieldContents,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ContentsValidator is a validator for the "contents" field. It is called by the builders before save.
	ContentsValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
