// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CodesColumns holds the columns for the "codes" table.
	CodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "contents", Type: field.TypeString, Size: 400000},
	}
	// CodesTable holds the schema information for the "codes" table.
	CodesTable = &schema.Table{
		Name:       "codes",
		Columns:    CodesColumns,
		PrimaryKey: []*schema.Column{CodesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CodesTable,
	}
)

func init() {
}
